# Generated by Django 5.0 on 2024-01-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_payment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax_date',
        ),
        migrations.AddField(
            model_name='order',
            name='tax_data',
            field=models.JSONField(blank=True, help_text="Data format :{'tax_type':{'tax_percentage':'tax_amount'}}", null=True),
        ),
    ]
